
#import FreeCAD
import Draft
import Spreadsheet
import math

def setObjColor(obj, color):
	# set color for all faces of selected object
	colorlist=[]
	for i in range(len(obj.Shape.Faces)):
		colorlist.append(color)
	print('[*] Object contains %d faces'%(len(colorlist),))
	obj.ViewObject.DiffuseColor = colorlist

#ザグリ穴用色変更関数
def setObjColor2(obj, color, color2):
	# set color for all faces of selected object
	colorlist=[]
	for i in range(len(obj.Shape.Faces)):
		colorlist.append(color)
	print('[*] Object contains %d faces'%(len(colorlist),))
	colorlist[2]=color2
	obj.ViewObject.DiffuseColor = colorlist

doc = App.ActiveDocument
dg = Draft.downgrade(App.ActiveDocument.ActiveObject, delete=True)

for upEdge in dg[0]:
   circle = Draft.upgrade(upEdge, delete=True)

#   Create Spreadsheet
sheet = App.ActiveDocument.addObject("Spreadsheet::Sheet","HoleDimensions")
sheet.Label = "Dimensions"

sheet.set('A1','x')
sheet.set('B1','y')
sheet.set('C1','z')
sheet.set('D1','D1')
sheet.set('E1','D2')
sheet.set('F1','H')
sheet.set('G1','Type')


i = 2
for cir in doc.findObjects(Name="Circle"):
   zoffset = -5		#extension length for bottom side
   H = 25			#Zaguri bottom hight
   d = cir.Radius * 2

#   detect Hole Type
   if d > round(d)-0.1 and d < round(d)+0.1:
      Type = "Dowel"
      D1 = round(d)
      D2 = D1 + 1
   else:
      Type = "Bolt"
      nominal = math.floor(cir.Radius) * 2
      D1 = nominal + 2
      D2 = nominal * 1.5 + 2

#   create Cylinder
   cyl = doc.addObject("Part::Cylinder","Cylinder1")
   cyl.Radius = D1 / 2
   cyl.Height = 200 + zoffset
   cyl.Placement.Base.x = cir.Placement.Base.x
   cyl.Placement.Base.y = cir.Placement.Base.y
   cyl.Placement.Base.z = zoffset

   cyl2 = doc.addObject("Part::Cylinder","Cylinder2")
   cyl2.Radius = D2 / 2
   cyl2.Height = cyl.Height - H
   cyl2.Placement.Base.x = cir.Placement.Base.x
   cyl2.Placement.Base.y = cir.Placement.Base.y
   cyl2.Placement.Base.z = H

#   cir.Placement.Base.z = 0
#   cir.Placement.Base

#   create Circle Center Point
   vtx = doc.addObject("Part::Vertex","Vertex")
   vtx.X = cir.Placement.Base.x
   vtx.Y = cir.Placement.Base.y

#   set Face Color
   if (Type == "Dowel"):
      setObjColor(cyl, (1.0 ,1.0 ,0.0))
      setObjColor(cyl2, (0.0 ,0.0 ,1.0))
   elif (Type == "Bolt"):
      setObjColor(cyl, (0.0 ,0.0 ,1.0))
      setObjColor2(cyl2, (0.0 ,0.0 ,1.0), (1.0, 0.0, 0.0))

#   Value set to Spreadsheet
   sheet.set('A'+str(i),str(cir.Placement.Base.x))
   sheet.set('B'+str(i),str(cir.Placement.Base.y))
   sheet.set('C'+str(i),str(cir.Placement.Base.z))
   sheet.set('D'+str(i),str(D1))
   sheet.set('E'+str(i),f'{D2}')
   sheet.set('F'+str(i),f'{H}')
   sheet.set('G'+str(i),Type)

#   set Alias
   sheet.setAlias('A' + str(i),'x' + str(i))

#   Object Property Link to Spreadsheet

   cyl.Placement.Base.x = cir.Placement.Base.x


   i += 1
FreeCAD.ActiveDocument.recompute()

