#import FreeCAD
import Draft
import Spreadsheet

doc = App.ActiveDocument
dg = Draft.downgrade(App.ActiveDocument.ActiveObject, delete=True)

for upEdge in dg[0]:
   circle = Draft.upgrade(upEdge, delete=True)

#   Create Spreadsheet
sheet = App.ActiveDocument.addObject("Spreadsheet::Sheet","MySpreadsheet")
sheet.Label = "Dimensions"

sheet.set('A1','x')
sheet.set('B1','y')
sheet.set('C1','z')

i = 2
for cir in doc.findObjects(Name="Circle"):
   cyl = doc.addObject("Part::Cylinder","Cylinder")
   cyl.Radius = 10
   cyl.Height = 200
   cyl.Placement.Base.x = cir.Placement.Base.x
   cyl.Placement.Base.y = cir.Placement.Base.y

#   cir.Placement.Base.z = 0
#   cir.Placement.Base

   vtx = doc.addObject("Part::Vertex","Vertex")
   vtx.X = cir.Placement.Base.x
   vtx.Y = cir.Placement.Base.y

#   Value set to Spreadsheet
   sheet.set('A'+str(i),cir.Placement.Base.x)
   i += 1
FreeCAD.ActiveDocument.recompute()
